name: Bug report
description: File a bug report
labels: [bug]
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: What happened? What did you expect to happen?
          placeholder: Tell us what you see
      validations:
          required: true
    - type: input
      id: version
      attributes:
          label: Extension version
          placeholder: e.g. 0.1.0
    - type: input
      id: browser
      attributes:
          label: Browser and version
          placeholder: e.g. Chrome 126
    - type: input
      id: os
      attributes:
          label: OS
          placeholder: e.g. Windows 11
    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
          placeholder: |
              1. Go to ...
              2. Click ...
              3. See ...
    - type: textarea
      id: logs
      attributes:
          label: Console logs / screenshots
          description: Please paste logs or attach screenshots if possible.
