name: Feature request
description: Suggest an idea for this project
labels: [feat]
body:
    - type: textarea
      id: problem
      attributes:
          label: Problem
          description: What problem are you trying to solve?
      validations:
          required: true
    - type: textarea
      id: solution
      attributes:
          label: Proposed solution
          description: What would you like to happen?
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
    - type: textarea
      id: context
      attributes:
          label: Additional context
